# Build the executable ggplot code chunk corresponding to `plot_gene()`.
# The variable assignments are handled in `generate_chunk()`, so this returns only the body.
generate_plot_gene_text_chunk <- function(template=NULL) {
  c(
    "# Build the plotting data frame.",
    "df <- data.frame(covar, Expression=exprs[id, ], check.names=FALSE)",
    "colnames(df)[ncol(df)] <- expressionLabel",
    "",
    "# Resolve the title from the annotation if it is available.",
    "if(!is.null(annot)) {",
    "  title <- sprintf(\"%s (%s)\", id, annot[match(id, annot[[annot_id_col]]), ][[annot_symb_col]])",
    "} else {",
    "  title <- id",
    "}",
    "",
    "# Keep manual color mappings stable for discrete variables.",
    "if(!is.na(colorBy) && is.list(colorScale) && identical(colorScale$type, \"manual\")) {",
    "  df[[colorBy]] <- as.character(df[[colorBy]])",
    "}",
    "",
    "# Build the ggplot mapping with only the aesthetics that are active.",
    "if(!is.na(colorBy)) {",
    "  if(!is.na(groupBy)) {",
    "    g <- ggplot2::ggplot(df, ggplot2::aes(x=.data[[xCovar]], y=.data[[yCovar]], group=.data[[groupBy]], color=.data[[colorBy]]))",
    "  } else {",
    "    g <- ggplot2::ggplot(df, ggplot2::aes(x=.data[[xCovar]], y=.data[[yCovar]], color=.data[[colorBy]]))",
    "  }",
    "} else {",
    "  if(!is.na(groupBy)) {",
    "    g <- ggplot2::ggplot(df, ggplot2::aes(x=.data[[xCovar]], y=.data[[yCovar]], group=.data[[groupBy]]))",
    "  } else {",
    "    g <- ggplot2::ggplot(df, ggplot2::aes(x=.data[[xCovar]], y=.data[[yCovar]]))",
    "  }",
    "}",
    "",
    "# Choose the main geometry from the current plot mode.",
    "if(!is.numeric(df[[xCovar]]) && is.na(groupBy)) {",
    "  if(categoricalPlot == \"box\") {",
    "    g <- g + ggplot2::geom_boxplot(outlier.shape=NA) + ggplot2::geom_jitter(size=3, alpha=.5, width=.1)",
    "  } else if(categoricalPlot == \"violin\") {",
    "    g <- g + ggplot2::geom_violin(trim=FALSE, alpha=.4) + ggplot2::geom_jitter(size=3, alpha=.5, width=.1)",
    "  } else if(categoricalPlot == \"raincloud\") {",
    "    g <- g +",
    "      gghalves::geom_half_violin(side=\"r\", trim=FALSE, alpha=.45, nudge=.08) +",
    "      ggplot2::geom_boxplot(width=.1, outlier.shape=NA, alpha=.75) +",
    "      ggdist::stat_dots(side=\"left\", dotsize=.2)",
    "  }",
    "} else {",
    "  if(!is.na(symbolBy)) {",
    "    g <- g + ggplot2::geom_point(ggplot2::aes(shape=.data[[symbolBy]]), size=3)",
    "  } else {",
    "    g <- g + ggplot2::geom_point(size=3)",
    "  }",
    "}",
    "",
    "# Add grouping, faceting, and color scale settings when requested.",
    "if(!is.na(groupBy)) {",
    "  g <- g + ggplot2::geom_line()",
    "}",
    "",
    "if(!is.na(trellisBy)) {",
    "  g <- g + ggplot2::facet_wrap(stats::as.formula(paste(\"~\", trellisBy)), scales=trellisScales)",
    "}",
    "",
    "if(!is.na(colorBy) && is.list(colorScale)) {",
    "  if(identical(colorScale$type, \"manual\") && length(colorScale$values) > 0L) {",
    "    g <- g + ggplot2::scale_color_manual(values=colorScale$values, drop=FALSE)",
    "  } else if(identical(colorScale$type, \"gradientn\") && length(colorScale$colours) > 1L) {",
    "    g <- g + ggplot2::scale_color_gradientn(colours=colorScale$colours, values=colorScale$values, limits=colorScale$limits)",
    "  }",
    "}",
    "",
    "# Finish the plot object and return it as the last expression.",
    "g <- g + ggplot2::ggtitle(title)",
    "if(isTRUE(transpose)) {",
    "  g <- g + ggplot2::coord_flip()",
    "}",
    "g"
  )
}
